#! /bin/bash

MODES_1D_PATH=./src/modes/lib_1d/
MODES_2D_PATH=./src/modes/lib_2d/

mkdir -p ./output/lib
rm -f ./output/lib/*

for f in $MODES_1D_PATH*.cpp; do 
    MODE=${f#${MODES_1D_PATH}}
    TMP=${MODE#*_}
    MODE_NAME=${TMP%.cpp} 

    ./tools/build_mode_1d $MODE_NAME
done

for f in $MODES_2D_PATH*.cpp; do
    MODE=${f#${MODES_2D_PATH}}
    TMP=${MODE#*_}
    MODE_NAME=${TMP%.cpp}

    ./tools/build_mode_2d $MODE_NAME
done


exit 0
